/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CustomMode: typeof import('./src/components/CustomMode.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobDescription: typeof import('./src/components/JobDescription.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubmissionForm: typeof import('./src/components/SubmissionForm.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
