/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    CustomMode: typeof import('./src/components/CustomMode.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobDescription: typeof import('./src/components/JobDescription.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubmissionForm: typeof import('./src/components/SubmissionForm.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UsingCustomMode: typeof import('./src/components/UsingCustomMode.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
