/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicantName: typeof import('./src/components/basic/ApplicantName.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BasicEmail: typeof import('./src/components/basic/BasicEmail.vue')['default']
    BasicFileUpload: typeof import('./src/components/basic/BasicFileUpload.vue')['default']
    BasicName: typeof import('./src/components/basic/BasicName.vue')['default']
    BasicSubmissionForm: typeof import('./src/components/BasicSubmissionForm.vue')['default']
    BasicSubmit: typeof import('./src/components/basic/BasicSubmit.vue')['default']
    Button: typeof import('primevue/button')['default']
    CustomFileUpload: typeof import('./src/components/custom/CustomFileUpload.vue')['default']
    CustomMode: typeof import('./src/components/CustomMode.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobDescription: typeof import('./src/components/other/JobDescription.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubmissionForm: typeof import('./src/components/SubmissionForm.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
